version: "3.8"
services:
  cassandra1:
    image: cassandra:4.1
    # container_name: cassandra1
    environment:
      - CASSANDRA_CLUSTER_NAME=demo-cluster
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RACK1
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      # - JVM_EXTRA_OPTS=-javaagent:/jmx_exporter/jmx_prometheus_javaagent-0.20.0.jar=7070:/jmx_exporter/config.yaml
    volumes:
      - cassandra1_data:/var/lib/cassandra
      - cassandra1_commitlog:/var/lib/cassandra/commitlog
      # - ./jmx_exporter:/jmx_exporter
    # networks:
    #   - cassandra-net
    ports:
      - "9042:9042"  # CQL
      - "7071:7070"  # JMX Exporter

  cassandra2:
    image: cassandra:4.1
    # container_name: cassandra2
    environment:
      - CASSANDRA_CLUSTER_NAME=demo-cluster
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RACK2
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      # - JVM_EXTRA_OPTS=-javaagent:/jmx_exporter/jmx_prometheus_javaagent-0.20.0.jar=7070:/jmx_exporter/config.yaml
    volumes:
      - cassandra2_data:/var/lib/cassandra
      - cassandra2_commitlog:/var/lib/cassandra/commitlog
      # - ./jmx_exporter:/jmx_exporter
    # networks:
    #   - cassandra-net
    ports:
      - "9142:9042"
      - "7072:7070"

  cassandra3:
    image: cassandra:4.1
    # container_name: cassandra3
    environment:
      - CASSANDRA_CLUSTER_NAME=demo-cluster
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RACK3
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      # - JVM_EXTRA_OPTS=-javaagent:/jmx_exporter/jmx_prometheus_javaagent-0.20.0.jar=7070:/jmx_exporter/config.yaml
    volumes:
      - cassandra3_data:/var/lib/cassandra
      - cassandra3_commitlog:/var/lib/cassandra/commitlog
      # - ./jmx_exporter:/jmx_exporter
    # networks:
    #   - cassandra-net
    ports:
      - "9242:9042"
      - "7073:7070"

  cassandra4:
    image: cassandra:4.1
    # container_name: cassandra4
    environment:
      - CASSANDRA_CLUSTER_NAME=demo-cluster
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RACK4
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      # - JVM_EXTRA_OPTS=-javaagent:/jmx_exporter/jmx_prometheus_javaagent-0.20.0.jar=7070:/jmx_exporter/config.yaml
    volumes:
      - cassandra4_data:/var/lib/cassandra
      - cassandra4_commitlog:/var/lib/cassandra/commitlog
      # - ./jmx_exporter:/jmx_exporter
    # networks:
    #   - cassandra-net
    ports:
      - "9342:9042"
      - "7074:7070"

  opscenter:
    image: datastax/ds-opscenter:6.5
    # container_name: opscenter
    ports:
      - "8888:8888"
    # networks:
    #   - cassandra-net

volumes:
  cassandra1_data:
  cassandra1_commitlog:
  cassandra2_data:
  cassandra2_commitlog:
  cassandra3_data:
  cassandra3_commitlog:
  cassandra4_data:
  cassandra4_commitlog:

networks:
  cassandra-net:
    driver: overlay
